[default]
auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 0
block_timestamp = 0
cache = true
evm_version = 'istanbul'
extra_output = []
extra_output_files = []
ffi = false
force = false
fuzz_max_global_rejects = 65536
fuzz_max_local_rejects = 1024
fuzz_runs = 256
gas_limit = 9223372036854775807
gas_price = 0
gas_reports = ['*']
ignored_error_codes = []
initial_balance = '0xffffffffffffffffffffffff'
libraries = []
libs = ['lib']
names = false
offline = false
optimizer = true
optimizer_runs = 999999
out = 'out'
remappings = ['ds-test/=lib/ds-test/src/']
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
sizes = false
src = 'src'
test = 'test'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
verbosity = 0
gas_reports = ["*"]

