name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup-nvm
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: v16.0.0

      - name: setup-yarn
        run: |
          npm i -g yarn@1.22.10
          yarn --version

      - name: setup-env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MAINNET_RPC_URL: https://mainnet.infura.io/v3/${{ secrets.API_KEY }}
          envkey_RINKEBY_RPC_URL: https://rinkeby.infura.io/v3/${{ secrets.API_KEY }}
          envkey_ROPSTEN_RPC_URL: https://ropsten.infura.io/v3/${{ secrets.API_KEY }}
          envkey_KOVAN_RPC_URL: https://kovan.infura.io/v3/${{ secrets.API_KEY }}
          envkey_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          envkey_ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          envkey_REPORT_GAS: ${{secrets.REPORT_GAS}}
          file_name: .env

      - name: build
        run: |
          yarn install
          yarn build
          # yarn build:contracts

      - name: test
          # yarn test
        run: PKG=@darwinia/contracts-verify yarn test

      - name: merge-gas-report
        run: yarn merge

      - name: codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
        run: npx codechecks
